services:
  erp_epmapat_be:
    build: erp_epmapat_be
    image: erp_epmapat_be
    container_name: erp_epmapat_be
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://192.168.0.69:5432/ErpEpmapaT
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=086411421
    ports: 
      - "8080:8080"
    restart: "always"
    networks:
      - erp_epmapat
networks:
  erp_epmapat:
    driver: bridge