spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ErpEpmapaT}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12345}

#abonados.fotos.base-path=C:/ERP/nube-local/abonados
storage.type=${STORAGE_TYPE:nextcloud}
nextcloud.base-url=${NEXTCLOUD_BASE_URL:https://192.168.0.52/nextcloud}
nextcloud.username=${NEXTCLOUD_USERNAME:admin}
nextcloud.password=${NEXTCLOUD_PASSWORD:Epmapat2026}
nextcloud.base-folder=${NEXTCLOUD_BASE_FOLDER:/EPMAPAT-PHOTOS}
nextcloud.ssl.trust-all=${NEXTCLOUD_SSL_TRUST_ALL:true}
