spring.jpa.database=POSTGRESQL
#spring.datasource.url=jdbc:postgresql://localhost:5432/ErpEpmapaT
#spring.datasource.url=jdbc:postgresql://162.252.82.34:5432/epmapa_tulcan
spring.datasource.url=jdbc:postgresql://192.168.0.88:5432/ErpEpmapaT
spring.datasource.username=postgres
#spring.datasource.username=tulcan

spring.datasource.password=Epmapat2024
#spring.datasource.password=12345
#spring.datasource.password=Eiy3eghi

spring.datasource.driver-class-name=org.postgresql.Driver
#server.port=9090
spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false


# Ruta donde se guardarán los archivos XML
xml.storage.path=./xml-storage

# Tamaño máximo para archivos subidos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# application.yml
