storage.type=${STORAGE_TYPE:nextcloud}
nextcloud.base-url=${NEXTCLOUD_BASE_URL:}
nextcloud.username=${NEXTCLOUD_USERNAME:}
nextcloud.password=${NEXTCLOUD_PASSWORD:${NEXTCLOUD_APP_TOKEN:}}
nextcloud.base-folder=${NEXTCLOUD_BASE_FOLDER:/EPMAPAT-PHOTOS}
nextcloud.ssl.trust-all=${NEXTCLOUD_SSL_TRUST_ALL:true}
